[package]
name = "thread_local_scope"
description = "Scoped access to thread local storage"
version = "0.1.0"
edition = "2024"
categories = ["rust-patterns"]
keywords = ["thread_local"]


[dev-dependencies]
trybuild = "1.0.114"
static_assertions = "1.1.0"
